DROP SCHEMA IF EXISTS markdown;

CREATE SCHEMA markdown;

USE markdown;

CREATE TABLE User(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Email VARCHAR(100) NOT NULL,
    Name VARCHAR(70) NOT NULL,
    Surname VARCHAR(70) NOT NULL,
    Username VARCHAR(20) NOT NULL,
    PasswordHash VARCHAR(60) NOT NULL,
    RegistrationDate DATETIME NOT NULL,
    Deleted BIT NOT NULL DEFAULT 0
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Document(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    IdUser INT NOT NULL,
    Markdown TEXT,
    
    FOREIGN KEY (IdUser) REFERENCES User(Id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
